### ISSUE TITLE
sign_keys: add key for zabbix 3.2 on stretch

### ISSUE THREAD

**Issue by cdelgehier** [dj-wasabi/ansible-zabbix-agent#114]
Hello

Could you add the sign_key for zabbix 3.2 on debian stretch ?

Thx

```yaml
---
sign_keys:
  "34":
    stretch:
      sign_key: A14FE591
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
    xenial:
      sign_key: E709712C
  "32":
    stretch:
      sign_key: A14FE591
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
    xenial:
      sign_key: E709712C
  "30":
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
    xenial:
      sign_key: E709712C
  "24":
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    precise:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
  "22":
    squeeze:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    precise:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
    lucid:
      sign_key: 79EA5ED4

suse:
  "openSUSE Leap":
    "42":
      name: server:monitoring
      url: http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_{{ ansible_distribution_version }}/
  "openSUSE":
    "12":
      name: server_monitoring
      url: http://download.opensuse.org/repositories/server:/monitoring/openSUSE_{{ ansible_distribution_version }}
  "SLES":
    "11":
      name: server_monitoring
      url: http://download.opensuse.org/repositories/server:/monitoring/SLE_11_SP3/
...
```
