### ISSUE TITLE
ListenIP should be left undefined by default and use zabbix-agent default.

### ISSUE THREAD

**Issue by dlbewley** [dj-wasabi/ansible-zabbix-agent#13]
If not defined in `zabbix-agentd.conf` then the `ListenIP` defaults to `0.0.0.0` (all interfaces). This should be the default. 

ListenIP should not be set UNLESS the playbook user defines a `agent_listeninterface`.

Instead the template attempts to insert an IP address from the ansible inventory in this field. The IP is referenced like this

```
{% if agent_listeninterface is defined and agent_listeninterface %}
ListenIP={{ hostvars[inventory_hostname]['ansible_'+ agent_listeninterface]['ipv4'].address }}
{% endif %}
```

The `agent_listeninterface` defaults to `eth0` so that evals to `{{ hostvars[inventory_hostname][ansible_eth0]['ipv4'].address }}` by default.

If your machine has no `eth0` then the playbook fails. This forces you to override a default variable to enter a non-default entry in the config file.

There's an attempt to avoid this problem with the if statement in the template, but that fails because the inner variable is interpolated first. Which fails and bombs the playbook.

**Comment by dlbewley** [comment]
I came up with this test playbook to work through the logic of a fix.

Normally the `agent_listeninterface` and `agent_listenip` vars should be left empty. If an interface is provided then the IP will be looked up, but if  `agent_listenip`  is defined, it will always be used.

If nothing is provided then the IP will default to _0.0.0.0_. This is the agent default, so adding it to the config will be redundant, but fine.

Technically, zabbix agent supports a list of listen IPs, but that feels less than necessary right now. Not to mention IPv6 is being ignored in this solution..

```yaml
---
- hosts: all
  vars:
    agent_listeninterface:
    agent_listenip:

  tasks:
  - name: "Fail invalid specified agent_listeninterface"
    fail:
      msg: "The specified network interface does not exist"
    when: "agent_listeninterface and (agent_listeninterface not in ansible_interfaces)"

  - name: "Get IP of agent_listeninterface when no agent_listenip specified"
    set_fact:
      agent_listenip: "{{ hostvars[inventory_hostname]['ansible_' + agent_listeninterface]['ipv4'].address | default('0.0.0.0') }}"
    when: "agent_listeninterface and not agent_listenip"

  - name: "Default agent_listenip to all when not specified"
    set_fact:
      agent_listenip: '0.0.0.0'
    when: "not agent_listenip"

  - name: "Fail invalid specified agent_listenip"
    fail:
      msg: "The agent_listenip does not exist"
    when: "agent_listenip != '0.0.0.0' and agent_listenip not in ansible_all_ipv4_addresses"

  - name: Results
    debug:
      msg: "Interface is {{agent_listeninterface}} and IP is {{ agent_listenip }}"
```

Template goes back to basic one liner
```
ListenIP={{ agent_listenip }}
```

PR coming soon.
