### ISSUE TITLE
'zabbix_short_version' is undefined

### ISSUE THREAD

**Issue by Sispheor** [dj-wasabi/ansible-zabbix-agent#134]
Hi!, I've downloaded the last release. Here is my playbook
```yml
- name: setup zabbix agent
  hosts: "{{ targets | default('zabbix-monitored') }}"
  remote_user: centos
  become: True
  gather_facts: True

  roles:
    - role: ansible-zabbix-agent
      zabbix_agent_server: zbx-it.domain.com
      zabbix_agent_serveractive: zbx-it.domain.com
      zabbix_version: 3.4
      zabbix_repo: epel
      zabbix_agent_tlspsk_secret: secret
      zabbix_host_groups:
         - Linux Servers
      zabbix_link_templates:
         - Template OS Linux
```

And my error
```
TASK [ansible-zabbix-agent : RedHat | Use EPEL package name] **********************************************************************************************************************************
fatal: [test-mysql-1]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'zabbix_short_version' is undefined\n\nThe error appears to have been in '/home/nico/Documents/ansible_community_roles/ansible-zabbix-agent/tasks/RedHat.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"RedHat | Use EPEL package name\"\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'zabbix_short_version' is undefined"}
```

Did I miss something?
