### ISSUE TITLE
The ipaddr filter requires python-netaddr be installed on the ansible controller

### ISSUE THREAD

**Issue by JensNeirynck** [dj-wasabi/ansible-zabbix-agent#200]
**Describe the bug**

I tried to install zabbix-agent with the configuration below.
But I'm getting the following error:
```
TASK [dj-wasabi.zabbix-agent : Get Total Private IP Addresses] *****************
fatal: [web1]: FAILED! => {"msg": "The ipaddr filter requires python-netaddr be installed on the ansible controller"}
```

**Installation method/version**
* Ansible Galaxy, role version: latest

**Ansible Version**

```
ansible --version
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

**Targetted hosts**
Concerns the following OS(es):
* CentOS

**Expected behavior**

**Additional context**
```
- hosts: all
  roles:
     - role: dj-wasabi.zabbix-agent
       zabbix_agent_server: 192.168.1.2
       zabbix_agent_serveractive: 192.168.1.2
       zabbix_url: 192.168.1.2/monitor
       zabbix_api_use: true
       zabbix_api_user: Admin
       zabbix_api_pass: zabbix
       zabbix_create_host: present
       zabbix_host_groups:
         - Webservers
       zabbix_link_templates:
         - Template OS Linux
         - Apache APP Template
       zabbix_macros:
         - macro_key: apache_type
           macro_value: reverse_proxy
```
