### ISSUE TITLE
Role Should NOT Smash Ansible Facts

### ISSUE THREAD

**Issue by fxfitz** [dj-wasabi/ansible-zabbix-agent#207]
**Describe the bug**
This role smashes `ansible_distribution_major_version`. This should not happen.

```
- name: "Fedora | Modify ansible_distribution_major_version and zabbix_agent_conf_dir when Fedora"
  set_fact:
    ansible_distribution_major_version: 7
  when:
    - ansible_distribution == "Fedora"
```

As you can see, this task sets the distribution to something else. When connecting to a Fedora machine, one would expect this to be something along the lines of "27" or "28" or "29" (for more recent version of Fedora). By changing this to "7" does *not* do what it's supposed to be.

**Installation method/version**
I'm using this as a Github source at hash: d691a6bc0da5c8eb58b1d9d5e09c7ee7d300ac8e

However this appears to be present in master.
**Ansible Version**

2.7

**Targetted hosts**

* Fedora
**Expected behavior**
The role works as I would expect on Fedora, but it has unintended consequences. Any tasks that run *after* this task, even outside this role in the same playbook, has the wrong distribution version.

**Additional context**
I believe this was introduced in #199
