### ISSUE TITLE
"create host" task sets the interface as the node that ansible is running on

### ISSUE THREAD

**Issue by tscully49** [dj-wasabi/ansible-zabbix-agent#259]
**Describe the bug**
When the role is creating the host in zabbix I notice it is setting the interface IP and DNS as the host that I am running the ansible command on, not the host the zabbix agent is running on.  This is causing me to have to go into zabbix and manually update the IP and DNS to the zabbix agent.  

**Installation method/version**
Github and Ansible Galaxy using 1.7.1

**Ansible Version**

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

**Targetted hosts**
Concerns the following OS(es):
* Rhel

**Expected behavior**
I'm expecting the interface in zabbix is set to the IP and DNS of the agent, not the ansible controller node. 

**Additional context**
I poked around some and it looks like the IP is being set in the /tasks/main.yml file at the "Set default ip address for zabbix_agent_ip" task.  
```
- name: "Set default ip address for zabbix_agent_ip"
  set_fact:
    zabbix_agent_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4'].address }}"
  when:
    - zabbix_agent_ip is not defined
    - "'ansible_default_ipv4' in hostvars[inventory_hostname]"
```
The problem here is **hostvars[inventory_hostname]['ansible_default_ipv4'].address** is the host that I am running the ansible playbook coommand on.  If I change that to **hostvars[inventory_hostname]['inventory_hostname']**, the correct IP address is set.  I'm also thinking if I set it just to **inventory_hostname** it would also work.  

As for the DNS, it looks like that is only being set in /defaults/main.yml at this block 
```
zabbix_agent_interfaces:
  - type: 1
    main: 1
    useip: "{{ zabbix_useuip }}"
    ip: "{{ zabbix_agent_ip }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ zabbix_agent_listenport }}"
```

Note: I do happen to have zabbix-agent running on the host that I am running the ansible command on, but I don't believe that should be affecting anything here.
