### ISSUE TITLE
Amazon Linux 1 get invalid repository

### ISSUE THREAD

**Issue by eduzuchetti** [dj-wasabi/ansible-zabbix-agent#269]
**Describe the bug**
When running on Amazon Linux 1 hosts, the version of release is "2018.03" instead of other values like "NA" or "2", and this value (2018) is set into the repo url.

Content of file /etc/yum.repos.d/zabbix.repo:
```
[zabbix]
name=Zabbix Official Repository - $basearch
**baseurl=http://repo.zabbix.com/zabbix/4.0/rhel/2018/$basearch/**
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591
```

This value is not one of the values on the file "roles/ansible-zabbix-agent/tasks/RedHat.yml" so then I added the rule below, and apparently worked correctly

```
- name: "RedHat | Set zabbix_agent_distribution_major_version to 6 when Major Version is 2018.03"
  set_fact:
    zabbix_agent_distribution_major_version: 6
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "2018"

```
