### ISSUE TITLE
create host doesn't appaer to run

### ISSUE THREAD

**Issue by gregf** [dj-wasabi/ansible-zabbix-agent#302]
**Describe the bug**
I'm trying to create hosts via the api after the agent is setup, but it never appears to run the api commands.

**Installation method/version**
* Ansible Galaxy, role version: 2.1.0

-->

**Ansible Version** 

```
ansible 2.9.4
  config file = /home/gregf/ownCloud/dev/active/hugops-infrastructure/ansible.cfg
  configured module search path = ['/home/gregf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
```
**Targetted hosts**

* Ubuntu 18.04LTS

**Expected behavior**
For the host to appear in zabbix after the playbook is run.

I have the following playbook.

```
  vars:
    zabbix_version: 4.4
    zabbix_agent_server: 10.0.0.105
    zabbix_agent_serveractive: 10.0.0.105
    zabbix_install_pip_packages: True
    zabbix_agent_firewall_enable: True
    zabbix_agent_firewall_source: 10.0.0.105
    zabbix_url: 'https://zabbix.example.com'
    zabbix_api_use: True
    zabbix_api_user: 'ansible'
    zabbix_api_pass: 'my_pass'
    zabbix_create_host: True
    zabbix_agent_tlsconnect: psk
    zabbix_agent_tlsaccept: psk
    zabbix_agent_tlspskidentity: default
    zabbix_agent_tlspskfile: '/etc/zabbix/zabbix_agentd.psk'
    zabbix_agent_tlspsk_secret: 'my_secret'
    zabbix_host_groups:
      - Linux Servers
    zabbix_link_templates:
      - Template OS Linux
  roles:
    - { role: dj-wasabi.zabbix-agent }
```

It converges fine, no errors. I first noticed none of the hosts were being added to zabbix. I ran it and there's no logs of the api commands even being run. I tried both True and true, wasn't sure the proper way in python honestly.
