### ISSUE TITLE
creating hosts / linking templates fails

### ISSUE THREAD

**Issue by kamilkrzeminski** [dj-wasabi/ansible-zabbix-agent#57]
I have issue similar to this [#31](https://github.com/dj-wasabi/ansible-zabbix-agent/issues/31), but now there's no Library folder anymore. 

```
    },
    "msg": "Hostgroup not found: Containers"
}
```
```
},
    "msg": "Template not found: Template App Zabbix Agent"
}
```

My config is:

- MacOS Sierra
- Ansible 2.2.0.0
- installed zabbix-api via pip
- dj-wasabi/ansible-zabbix-agent v0.9
- Zabbix 3.2

My code:
```
    - role: dj-wasabi.zabbix-agent
      agent_server: "{{monitoring_server_ip}}"
      agent_serveractive: "{{monitoring_server_ip}}"
      zabbix_repo: zabbix
      zabbix_url: "{{monitoring_server_url}}"
      zabbix_api_use: true
      zabbix_api_user: "{{monitoring_api_user}}"
      zabbix_api_pass: "{{monitoring_api_password}}"
      zabbix_create_host: present
      zabbix_api_create_hosts: True
      zabbix_host_groups:
        - Containers
      zabbix_link_templates: 
        - "Template App Zabbix Agent"
```

Both group and template exist.
