### ISSUE TITLE
zabbix_agent_listenip not working as expected

### ISSUE THREAD

**Issue by dsteinkopf** [dj-wasabi/ansible-zabbix-agent#98]
I tried to set `zabbix_agent_listenip: 192.168.40.66` in a `host_vars/omvsrv`. I hoped this would set `ListenIP` in `zabbix_agentd.conf`. But this only resulted in 

```
TASK [dj-wasabi.zabbix-agent : Fail invalid specified agent_listenip] ***********************************************************************************************************
fatal: [omvsrv]: FAILED! => {"changed": false, "failed": true, "msg": "The agent_listenip does not exist"}
```

The following change in `/etc/ansible/roles/dj-wasabi.zabbix-agent/tasks/main.yml` helped:
```
--- /etc/ansible/roles/dj-wasabi.zabbix-agent/tasks/main.yml.orig2      2017-09-01 06:54:56.994328475 +0200
+++ /etc/ansible/roles/dj-wasabi.zabbix-agent/tasks/main.yml    2017-09-01 06:55:26.506420556 +0200
@@ -92,6 +92,7 @@
     msg: "The agent_listenip does not exist"
   when:
     - zabbix_agent_listenip != '0.0.0.0'
+    - (zabbix_agent_listenip not in ansible_all_ipv4_addresses)
   tags:
     - zabbix-agent
     - config 
```

Maybe this is what you had in mind when writing this check task.

**Comment by dj-wasabi** [comment]
Yes, thank you. Have created a PR for this.

**Comment by dj-wasabi** [comment]
And merged it. Thanks!

**Comment by dsteinkopf** [comment]
Thank you very much!
When are you planing to push this (and the other recent fixes) to ansible galaxy?

**Comment by dsteinkopf** [comment]
Using V1.0.2 from ansible galaxy, I still get the message "The agent_listenip does not exist".

File `/etc/ansible/roles/dj-wasabi.zabbix-agent/tasks/main.yml` still look like this:
```
...
- name: "Fail invalid specified agent_listenip"
  fail:
    msg: "The agent_listenip does not exist"
  when:
    - zabbix_agent_listenip != '0.0.0.0'
  tags:
    - zabbix-agent
    - config
...
```

Did you intentionally omit the line I suggested? `- (zabbix_agent_listenip not in ansible_all_ipv4_addresses)` ?
